-- MySQL Script generated by MySQL Workbench
-- Fri Nov 18 21:03:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `CPF` CHAR(11) NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Endereco` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE_CLIENTE` (
  `Numero` VARCHAR(10) NOT NULL,
  `DDD` CHAR(3) NOT NULL,
  `CLIENTE_CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`Numero`, `DDD`, `CLIENTE_CPF`),
  INDEX `fk_TELEFONE_CLIENTE_CLIENTE1_idx` (`CLIENTE_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_TELEFONE_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_CPF`)
    REFERENCES `mydb`.`CLIENTE` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AEROPORTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AEROPORTO` (
  `Codigo` INT NOT NULL,
  `Nome` VARCHAR(150) NOT NULL,
  `Localizacao` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VOO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VOO` (
  `NumVoo` INT NOT NULL,
  `Companhia` VARCHAR(100) NOT NULL,
  `Horario` TIME NOT NULL,
  `Destino` VARCHAR(250) NOT NULL,
  `AEROPORTO_Codigo` INT NOT NULL,
  PRIMARY KEY (`NumVoo`, `AEROPORTO_Codigo`),
  INDEX `fk_VOO_AEROPORTO1_idx` (`AEROPORTO_Codigo` ASC) VISIBLE,
  CONSTRAINT `fk_VOO_AEROPORTO1`
    FOREIGN KEY (`AEROPORTO_Codigo`)
    REFERENCES `mydb`.`AEROPORTO` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PASSAGEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PASSAGEM` (
  `Numero` INT NOT NULL AUTO_INCREMENT,
  `Data_Passagem` DATE NOT NULL,
  `Classe` VARCHAR(50) NOT NULL,
  `Preco` DOUBLE NOT NULL,
  `Poltrona` VARCHAR(50) NOT NULL,
  `CLIENTE_CPF` CHAR(11) NOT NULL,
  `VOO_NumVoo` INT NOT NULL,
  PRIMARY KEY (`Numero`),
  INDEX `fk_PASSAGEM_CLIENTE1_idx` (`CLIENTE_CPF` ASC) VISIBLE,
  INDEX `fk_PASSAGEM_VOO1_idx` (`VOO_NumVoo` ASC) VISIBLE,
  CONSTRAINT `fk_PASSAGEM_CLIENTE1`
    FOREIGN KEY (`CLIENTE_CPF`)
    REFERENCES `mydb`.`CLIENTE` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PASSAGEM_VOO1`
    FOREIGN KEY (`VOO_NumVoo`)
    REFERENCES `mydb`.`VOO` (`NumVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AVIAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AVIAO` (
  `NumAviao` INT NOT NULL,
  `Fabricante` VARCHAR(50) NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `Capacidade` INT NOT NULL,
  `VOO_NumVoo` INT NULL,
  PRIMARY KEY (`NumAviao`),
  INDEX `fk_AVIAO_VOO1_idx` (`VOO_NumVoo` ASC) VISIBLE,
  CONSTRAINT `fk_AVIAO_VOO1`
    FOREIGN KEY (`VOO_NumVoo`)
    REFERENCES `mydb`.`VOO` (`NumVoo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- AOP2 INSERÇÃO DE DADOS --

-- TABELA CLIENTE --

INSERT INTO mydb.CLIENTE(CPF, Nome, Endereco)
VALUES ('12345678901', 'João', 'Avenida João Da Silva');

INSERT INTO mydb.CLIENTE(CPF, Nome, Endereco)
VALUES ('42303946334', 'Maria', 'Avenida Maria Da Silva');

INSERT INTO mydb.CLIENTE(CPF, Nome, Endereco)
VALUES ('39420392834', 'José', 'Avenida José Da Silva');

INSERT INTO mydb.CLIENTE(CPF, Nome, Endereco)
VALUES ('00452134021', 'Júlia', 'Avenida Júlia Da Silva');

INSERT INTO mydb.CLIENTE(CPF, Nome, Endereco)
VALUES ('69304839201', 'Maurício', 'Avenida Maurício Da Silva');

SELECT * FROM mydb.CLIENTE;

-- TABELA TELEFONE_CLIENTE --

INSERT INTO mydb.TELEFONE_CLIENTE(CLIENTE_CPF, Numero, DDD)
VALUES ('12345678901', '1111111111', '027');

INSERT INTO mydb.TELEFONE_CLIENTE(CLIENTE_CPF, Numero, DDD)
VALUES ('42303946334', '2222222222', '022');

INSERT INTO mydb.TELEFONE_CLIENTE(CLIENTE_CPF, Numero, DDD)
VALUES ('39420392834', '3333333333', '033');

INSERT INTO mydb.TELEFONE_CLIENTE(CLIENTE_CPF, Numero, DDD)
VALUES ('00452134021', '4444444444', '044');

INSERT INTO mydb.TELEFONE_CLIENTE(CLIENTE_CPF, Numero, DDD)
VALUES ('69304839201', '5555555555', '055');

SELECT * FROM mydb.TELEFONE_CLIENTE;

-- TABELA AEROPORTO --

INSERT INTO mydb.AEROPORTO(Codigo, Nome, Localizacao)
VALUES (1234, 'Denver', 'EUA');

INSERT INTO mydb.AEROPORTO(Codigo, Nome, Localizacao)
VALUES (4321, 'Havana', 'Cuba');

INSERT INTO mydb.AEROPORTO(Codigo, Nome, Localizacao)
VALUES (1212, 'Kingston', 'Jamaica');

INSERT INTO mydb.AEROPORTO(Codigo, Nome, Localizacao)
VALUES (5858, 'Cidade do Panamá', 'Panamá');

INSERT INTO mydb.AEROPORTO(Codigo, Nome, Localizacao)
VALUES (9494, 'San Jose', 'Costa Rica');

SELECT * FROM mydb.AEROPORTO;

-- TABELA VOO --

INSERT INTO mydb.VOO(NumVoo, Companhia, Horario, Destino, AEROPORTO_Codigo)
VALUES (12, 'Azul', '14:05:04', 'EUA', 1234);

INSERT INTO mydb.VOO(NumVoo, Companhia, Horario, Destino, AEROPORTO_Codigo)
VALUES (43, 'LATAM', '20:05:04', 'Cuba', 4321);

INSERT INTO mydb.VOO(NumVoo, Companhia, Horario, Destino, AEROPORTO_Codigo)
VALUES (10, 'COPA', '04:05:04', 'Panamá', 1212);

INSERT INTO mydb.VOO(NumVoo, Companhia, Horario, Destino, AEROPORTO_Codigo)
VALUES (58, 'PASSAREDO', '08:05:04', 'Jamaica', 5858);

INSERT INTO mydb.VOO(NumVoo, Companhia, Horario, Destino, AEROPORTO_Codigo)
VALUES (94, 'Azul', '14:05:04', 'Costa Rica', 9494);

SELECT * FROM  mydb.VOO;

-- TABELA PASSAGEM --

INSERT INTO mydb.PASSAGEM (Data_Passagem, Classe, Preco, Poltrona, CLIENTE_CPF, VOO_NumVoo)
VALUES ('2002-05-29', 'VIP', 50.99, 'Reclinável', '12345678901', 12);

INSERT INTO mydb.PASSAGEM (Data_Passagem, Classe, Preco, Poltrona, CLIENTE_CPF, VOO_NumVoo)
VALUES ('2005-05-31', 'MASTER', 100.99, 'Reclinável', '42303946334', 43);

INSERT INTO mydb.PASSAGEM (Data_Passagem, Classe, Preco, Poltrona, CLIENTE_CPF, VOO_NumVoo)
VALUES ('2010-02-20', 'NORMAL', 24.99, 'Reclinável', '39420392834', 10);

INSERT INTO mydb.PASSAGEM (Data_Passagem, Classe, Preco, Poltrona, CLIENTE_CPF, VOO_NumVoo)
VALUES ('1998-05-29', 'VIP', 50.99, 'Reclinável', '00452134021', 58);

INSERT INTO mydb.PASSAGEM (Data_Passagem, Classe, Preco, Poltrona, CLIENTE_CPF, VOO_NumVoo)
VALUES ('2006-05-29', 'MASTER', 100.99, 'Reclinável', '69304839201', 94);


SELECT * FROM mydb.PASSAGEM;

-- TABELA AVIÃO --

INSERT INTO mydb.AVIAO(NumAviao, Fabricante, Tipo, Capacidade, VOO_NumVoo)
VALUES (101, 'NACIONAL', 'PLANADOR', 100, 12);

INSERT INTO mydb.AVIAO(NumAviao, Fabricante, Tipo, Capacidade, VOO_NumVoo)
VALUES (102, 'GALEÃO', 'PLANADOR', 250, 43);

INSERT INTO mydb.AVIAO(NumAviao, Fabricante, Tipo, Capacidade, VOO_NumVoo)
VALUES (103, 'JS', 'PLANADOR', 140, 10);

INSERT INTO mydb.AVIAO(NumAviao, Fabricante, Tipo, Capacidade, VOO_NumVoo)
VALUES (104, 'NEIVA', 'CARGA', 50, 58);

INSERT INTO mydb.AVIAO(NumAviao, Fabricante, Tipo, Capacidade, VOO_NumVoo)
VALUES (105, 'DP', 'AIRCRAFT', 200, 94);


SELECT * FROM mydb.AVIAO;


-- CRIAÇÃO DE UMA VIEW--

CREATE VIEW Vw_Informacoes_Cliente AS
SELECT mydb.TELEFONE_CLIENTE.DDD AS DDD,
mydb.TELEFONE_CLIENTE.Numero AS TELEFONE,
mydb.CLIENTE.CPF AS CPF,
mydb.CLIENTE.Nome AS NOME,
mydb.CLIENTE.Endereco AS ENDERECO
FROM TELEFONE_CLIENTE
INNER JOIN CLIENTE
ON mydb.CLIENTE.CPF = mydb.TELEFONE_CLIENTE.CLIENTE_CPF;

SELECT DDD, TELEFONE, NOME, CPF, ENDERECO
FROM Vw_Informacoes_Cliente;

-- CRIAÇÃO DE UMA TABELA DE LOG --

CREATE TABLE LOG (
LOG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
Usuario_Conectado CHAR(250) NOT NULL,
DATA_LOG DATE NOT NULL DEFAULT(CURRENT_DATE),
TIME_LOG TIME NOT NULL DEFAULT(CURRENT_TIME)
);

CREATE TRIGGER TG_Mensagem_Log_Cliente
AFTER DELETE ON mydb.CLIENTE
FOR EACH ROW
INSERT INTO LOG(Usuario_Conectado) 
VALUES(USER());

DELETE FROM mydb.CLIENTE
WHERE Nome = 'João';

SELECT * FROM LOG;

-- CRIAÇÃO DE UMA FUNCTION --

CREATE FUNCTION Fnc_SOMA_TOTAL_CAPACIDADE_AVIOES()
RETURNS INT
DETERMINISTIC
RETURN 
(SELECT SUM(mydb.AVIAO.Capacidade)
FROM mydb.AVIAO);

SELECT Fnc_SOMA_TOTAL_CAPACIDADE_AVIOES() AS TOTAL;


-- CRIAÇÃO DE UMA PROCEDURE -- 

CREATE PROCEDURE PR_Ver_Preco_Passagem(VARPreco FLOAT)
SELECT CONCAT('O preço da Passsagem é: R$ ', mydb.PASSAGEM.Preco) AS PRECO
FROM mydb.PASSAGEM
WHERE mydb.PASSAGEM.Numero = VARPreco;

CALL PR_Ver_Preco_Passagem(2);
